name: test

on:
  push:
    branches: [master, main]
  pull_request:
  workflow_dispatch:

jobs:
  client:
    uses: egao1980/cl-repository/.github/workflows/test-system.yml@main
    with:
      system: http2/client

  server:
    uses: egao1980/cl-repository/.github/workflows/test-system.yml@main
    with:
      system: http2/server/threaded
